import prisma from './client.js';

/**
 * Create a workflow with an immutable version
 */
export async function createWorkflow(data) {
  return prisma.workflow.create({
    data: {
      name: data.name,
      description: data.description,
      // version is auto-generated by @default(uuid())
    },
  });
}

/**
 * Update a workflow (version is excluded - immutable)
 */
export async function updateWorkflow(id, data) {
  // Explicitly exclude version to ensure immutability
  const { version, ...updateData } = data;
  
  return prisma.workflow.update({
    where: { id },
    data: updateData,
  });
}

/**
 * Get workflow by version (for version-based lookups)
 */
export async function getWorkflowByVersion(version) {
  return prisma.workflow.findUnique({
    where: { version },
  });
}
